// Builds the distributable bookmarklet from bookmarklet/src.js and injects it
// into index.html. Run: node build.cjs

const fs = require("fs");
const path = require("path");

const root = __dirname;
const srcPath = path.join(root, "bookmarklet", "src.js");
const distPath = path.join(root, "bookmarklet", "dist.txt");
const htmlPath = path.join(root, "index.html");

const src = fs.readFileSync(srcPath, "utf8");

// Light, safe minification: drop full-line comments and blank lines, trim each
// line, and keep newlines (so any inline comments stay harmless). No tokenizing
// so we never risk corrupting strings or regexes.
const minified = src
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => l.length > 0 && !l.startsWith("//"))
  .join("\n");

const wrapped = "void function(){" + minified + "}();";
const href = "javascript:" + encodeURIComponent(wrapped);

fs.writeFileSync(distPath, href + "\n");

// In-page runner for the extension (injected into x.com tabs).
const injectDir = path.join(root, "extension", "inject");
const injectPath = path.join(injectDir, "xbe-page.js");
fs.mkdirSync(injectDir, { recursive: true });
fs.writeFileSync(
  injectPath,
  "// Auto-generated by build.cjs — do not edit.\nvoid function(){\n" + minified + "\n}();\n"
);

if (fs.existsSync(htmlPath)) {
  let html = fs.readFileSync(htmlPath, "utf8");
  const re = /(id="xbe-bookmarklet"[^>]*\shref=")[^"]*(")/;
  if (!re.test(html)) {
    console.error("Could not find the bookmarklet anchor in index.html (id=\"xbe-bookmarklet\").");
    process.exit(1);
  }
  html = html.replace(re, `$1${href}$2`);
  fs.writeFileSync(htmlPath, html);
  console.log("Injected bookmarklet into index.html");
}

console.log(`Bookmarklet built: ${href.length} chars (source ${src.length} -> minified ${minified.length}).`);
console.log(`Saved raw URL to ${path.relative(root, distPath)}`);
console.log(`Wrote extension inject script to ${path.relative(root, injectPath)}`);
